name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create Docker Network
        run: make network-create  # Create Docker network

      - name: Create Docker Volume
        run: make volume-create  # Create Docker volume

      - name: Pull Postgres Image
        run: make db-pull  # Pull the Postgres image

      - name: Run Full Setup
        run: make setup