name: CI Pipeline

on:
  push:
    paths:
      - 'Milestone-4/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Pull Postgres image
        run: make db-pull
      
      - name: Create Docker network
        run: make network-create
      
      - name: Create Docker volume
        run: make volume-create
      
      - name: Build Docker image
        run: make app-build
      
      - name: Run Database Migration
        run: make app-migrate
      
      - name: Push Docker image to GHCR
        run: |
          docker tag flask-app:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/flask-app:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/flask-app:${{ github.sha }}

      - name: Clean up Docker containers and network
        run: make clean
