name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create Docker Network
        run: make -C Milestone-4 network-create

      - name: Create Docker Volume
        run: make -C Milestone-4 volume-create 

      - name: Run Full Setup
        run: make -C Milestone-4 setup