name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Pull Postgres image
        run: make -C Milestone-4 db-pull
      
      - name: Create Docker network
        run: make -C Milestone-4 network-create
      
      - name: Create Docker volume
        run: make -C Milestone-4 volume-create
      
      - name: Build Docker image
        run: make -C Milestone-4 app-build
      
      - name: Run Database Migration
        run: |
          docker exec app sh -c "\
            if [ ! -d migrations/versions ] || [ -z \"\`ls migrations/versions 2>/dev/null\`\" ]; then \
              echo 'No migrations found. Initializing...'; \
              python -m flask db init && \
              python -m flask db migrate --message 'Initial migration' && \
              python -m flask db upgrade; \
            else \
              echo 'Migrations found. Upgrading...'; \
              python -m flask db stamp head && \
              python -m flask db upgrade; \
            fi"

      
      - name: Push Docker image to GHCR
        run: |
          docker tag flask-app:${{ github.sha }} ghcr.io/${{ github.actor }}/flask-app:${{ github.sha }}
          docker push ghcr.io/${{ github.actor }}/flask-app:${{ github.sha }}


      - name: Clean up Docker containers and network
        run: make clean
